### ISSUE TITLE
BIMA SONG & HERACLES

### ISSUE THREAD

**Issue by ValerieKostiuk** [LerkaKostuik/Course-work#1]
Не могу понять, какой именно fits мне нужен из [BIMA SONG](https://ned.ipac.caltech.edu/level5/March02/SONG/SONG.html)?
Не могу найти данные  [HERACLES](https://www.cv.nrao.edu/~aleroy/heracles_data/)

**Comment by Amarchuk** [comment]
Про BIMA - CO datacube думаю подходит.

HERACLES данные есть в NED - находите по имени и дальше в [images](https://ned.ipac.caltech.edu/byname?objname=n3627&hconst=67.8&omegam=0.308&omegav=0.692&wmap=4&corr_z=1).

**Comment by ValerieKostiuk** [comment]
Fits из BIMA здесь почему-то не хочет открываться, хотя я открывала в ds9 и там всё нормально.

**Comment by Amarchuk** [comment]
Здесь в смысле в ноутбуке? Опять же, пишите в чем проблема

**Comment by ValerieKostiuk** [comment]
В этом файле оказалось как бы трёхмерное изображение. (Всё изображение можно разделись на 51 слой ). Возникает вопрос,что именно нам понадобиться

**Comment by Amarchuk** [comment]
Давайте его пока не трогать, и используем только HERACLES. Я может потом гляну в чем дело.
