### ISSUE TITLE
нижний квадрат и критерий Тумре

### ISSUE THREAD

**Issue by Amarchuk** [LerkaKostuik/Course-work#10]
Размышляя о том, что и как писать в статье по результатам этой работы и разглядывая картинки, я понял что нужно выяснить, почему нижний квадрат дает такие странные результаты (весь насыщен неустойчивостью). 

Например на нижних картинках в `get_data.ipynb` нижний левый угол по всем параметрам не отличается (насколько я могу судить) от правого верхнего. Единственное исключение - это эпициклическая частота (расстояние определенно разное). При этом внизу все неустойчиво, наверху - устойчиво. Интересный вопрос - почему так?

Единственный способ как это посмотреть явно, что я сейчас вижу - надергать с десяток пикселей из нижнего квадрата и парочку из верхнего правого угла, написать какие в них все величины и порисовать графики Q(k) (те, на которых мы ищем максимум). Возможно Вы придумаете что-то лучше, но выяснить это необходимо.

**Comment by ValerieKostiuk** [comment]
`надергать с десяток пикселей из нижнего квадрата и парочку из верхнего правого угла, написать какие в них все величины`
 Я попробовала сделать как вы написали, но ничего особенного в различии величин я не заметила. Затем я попробовала сделать то же самое только для пикселей с одним и тем же значением для эпициклической частоты. Далее я заметила, что ложный сигнал у нас появляется при маленьких значениях для оценок дисперсии звёздных скоростей. Далее я на карте отметила те пиксели, на которых маленькие значения этой дисперсии и они правда совпали с ложным сигналом. 
Думаю мне стоит скачать карту с ошибками для дисперсии и посмотреть на неё. Может и правда всё дело в этих данных? Ведь в других критериях я их не использую.

**Comment by Amarchuk** [comment]
Добрый день, 

Я честно не смог найти в ноутбуках, где это сделано (кроме перечисления пикселей, но так конечно их тяжело проанализировать).

Гипотеза хорошая, думаю действительно пора посмотреть на карту ошибок. Я могу посоветовать посмотреть среднее и дисперсию (ошибок) по каждому квадрату

**Comment by ValerieKostiuk** [comment]
`Я честно не смог найти в ноутбуках, где это сделано `
Извините, забыла указать где эта карта. Это в Toomre.ipynb в ячейке 31.

**Comment by Amarchuk** [comment]
Обратил на нее внимание, спасибо. Т.е. условно `Sigma_R<30` именно там, где неуст. Выглядит слишком подозрительно, чтобы не оказаться правдой :) Надо смотреть на ошибки, сами значения `sigma_s` вроде не какие-то необычные.

**Comment by ValerieKostiuk** [comment]
Здравствуйте!
Я скачала и просмотрела карту ошибок дисперсии. В Toomre.ipynb я попробовала сравнить эту карту с картой параметра Тумре. Только вот не смогла найти в статье, в каких единицах измерения я загрузила эти ошибки.

**Comment by Amarchuk** [comment]
Здравствуйте,

Эти ошибки все в тех же величинах км/с. Сравнение я посмотрел - интересно, надо только еще поделить одну карту на другую, чтобы сравнить еще относительные ошибки

**Comment by ValerieKostiuk** [comment]
Я построила карту относительных ошибок, она и правда очень хорошо коррелирует с областями ложной неустойчивости.

**Comment by Amarchuk** [comment]
Карту посмотрел - впечатляет! Т.е. в нижнем квадрате ошибки повсеместно по 150-200% и очевидно нельзя считать что у нас хоть какие-то данные там есть. Можно считать  этот вопрос решенным (только в результаты карту добавьте пожалуйста).
