### ISSUE TITLE
images

### ISSUE THREAD

**Issue by ValerieKostiuk** [LerkaKostuik/Course-work#2]
Подскажите, как вы вставляете картинки PDF в Jupyter?

**Comment by Amarchuk** [comment]
@LerkaKostuik, вроде бы `wand` работал хорошо

https://stackoverflow.com/questions/19470099/view-pdf-image-in-an-ipython-notebook

**Comment by ValerieKostiuk** [comment]
> @LerkaKostuik, вроде бы `wand` работал хорошо
> 
> https://stackoverflow.com/questions/19470099/view-pdf-image-in-an-ipython-notebook

Я попыталась вставить одну из pdf, но у меня почему-то не получилось

**Comment by Amarchuk** [comment]
Пишите ошибку или погуглите её (а еще можете попробовать второй упомянутый там способ). Самый простой, но неэлегантный способ - сохраните как картинку то что надо и не парьтесь с pdf.
