### ISSUE TITLE
Большая полуось

### ISSUE THREAD

**Issue by ValerieKostiuk** [LerkaKostuik/Course-work#5]
У меня возникли проблемы с большой полуосью. Как я понимаю, мне нужно взять большую полуось с PA=178(у меня кривая скорости построена по этой оси). А конкретно я не понимаю, как мне провести линию, соответствующую большой полуоси поверх моих изображений. Я, конечно, могу это попробовать сделать на глаз, но не уверена, что это честно.

**Comment by Amarchuk** [comment]
На глаз на самом деле (учитывая точность определения position angle) должно быть более-менее. Но я бы делал так: определяете направление на север и проводите строго линию с таким углом. Затем берете карту звездных скоростей NGC3627_map_vstar.fits (ну или газа) и смотрите, что линия прошла хорошо и все разделилось (там будет понятно, надеюсь, выглядит что так). 

Еще для проверки можно будет вырезать скорости из HI карты и сравнить с кривой вращения. Если все похоже - то значит провели правильно.

Еще вариант - пока не рисовать, а использовать простые значения (3), где не требуется PA.

Если рассуждения про скорости непонятны (почему и что там разделяется) - я напишу.

**Comment by ValerieKostiuk** [comment]
Посмотрите, пожалуйста, что у меня получилось. 
Я пыталась найти центр галактики честно, но в итоге пришлось искать его на глаз.
Мне кажется получился полный бред и я что-то не так понимаю(

**Comment by Amarchuk** [comment]
А зеленая точка - это что такое?

Я понял почему мне не приходилось для 628 решать эту задачу - у них в https://iopscience.iop.org/article/10.1088/0004-6256/145/5/138/pdf на Рис. 16 была линия P.A., т.е. я ее просто взял оттуда.

В статье у них написано, что 
> All maps presented in this paper have north pointing up and east pointing left.

Я открыл в ds9 с сеткой, и похоже что это и правда так. Так что вам просто надо найти центр и нарисовать линию через нее с углом PA. 

Кстати у них в Table 1 угол наклона 65 deg и PA=173 deg.

**Comment by Amarchuk** [comment]
Про центр: мне кажется что вот `WCS.wcs.crval` как в `cut_fits` должно работать (надо экспериментировать), но если нет - то и так центр на мой взгляд найдет довольно точно.

**Comment by ValerieKostiuk** [comment]
Я взяла большую полуось с PA=178, чтобы было с чем сравнивать. Правда у меня получилось, что эти две кривые не очень хорошо друг на друга накладываются(  
Судя по моей получившейся кривой скоростей, центр вроде попал куда нужно.( я использовала WCS.wcs.crval) 
А при вычислении кривой скоростей, мы учитываем скорости, которые на малой полуоси? Если да, то я поняла, почему у меня эти кривые скоростей не хорошо получаются.

**Comment by Amarchuk** [comment]
Мне кажется все хорошо и правдоподобно вышло. Вы молодец!

Со скоростями: они и не должны точно совпадать, вы же использовали другие данные (тут H_alpha, насколько я вижу, а там CO). Но они достаточно близки и похожи, чтобы считать тест успешным.

Вопрос про малую полуось я не понял.

**Comment by ValerieKostiuk** [comment]
Я посчитала эпициклическую частоту по тем значениям скорости, которые я получила, сделав разрез данных скоростей HI по большой полуоси . Я построила график и мне он не очень понравился. Посмотрите на него, пожалуйста.

**Comment by Amarchuk** [comment]
Так там же не HI данные? Вроде же Halpha. А с ними сложнее (в смысле это конечно газ излучает, но газ ионизированный звездами, а HI - это 21 см линия в радио диапазоне). Попробуйте все же HI вырезать, если вам снятая кривая вращения не зашла (мне в целом Ваша идея нравится - так у нас будет точно для всего нужного диапазона расстояний данные).

Что же до того, что вышла не очень эпициклическая частота - это на самом деле странно, кажется что достаточно гладкое приближение, чтобы такого не было. Можно попробовать брать в приближении полином меньшей степени (например 5ой).

**Comment by ValerieKostiuk** [comment]
Почему не HI данные?Я же ведь делаю срез вдоль большой полуоси по данным скоростей из каталога THINGS.

**Comment by Amarchuk** [comment]
Да, правда, меня запутали параметры. Тогда все отлично, надо только еще поделить ее на sin(i) и приблизить полиномом меньшей степени.

**Comment by Amarchuk** [comment]
(просто надо понимать - то, что эпициклическая частота получилась такой "рваной" - это именно что мы взяли слишком подробную модель и все эти повороты отражают именно тот факт, что модель "переобучена" на данных. Очень часто вообще берут степенную функцию для приближения - вон у Леруа тоже она очень простая)
