### ISSUE TITLE
Размерности

### ISSUE THREAD

**Issue by ValerieKostiuk** [LerkaKostuik/Course-work#6]
У меня вроде есть все данные, теперь мне осталось проверить их размерности, чтобы их подставить в конечную формулу. В конце файла main_program.ipynb я вывела гистограммы всех данных.
Можете посмотреть, может быть значения каких-нибудь величин будут вас смущать.

**Comment by Amarchuk** [comment]
Это не гистограммы в общем смысле) Просто двумерный массив данных.

Sigma_s - мне кажется там что-то маленькие значения. Sigma_HI и sigma_HI - наоборот большие (хотя дисперсии я посмотрел в [других галактиках](https://arxiv.org/pdf/1511.06006.pdf) - теоретически такое может быть). И формул перевода в физические величины (и самого перевода) я в ноутбуке не увидел. Если что - указание на все нужные  формулы вроде есть в моей статье по 628.

**Comment by Amarchuk** [comment]
Да, еще такое замечание: т.к. эта галактика есть у Леруа, то по размерностям можно смотреть еще его рисунки (Рис. 41 вот тут https://iopscience.iop.org/article/10.1088/0004-6256/136/6/2782/pdf). И формулы тоже все почти из его работы. 

У него кстати получился устойчивый диск.

**Comment by ValerieKostiuk** [comment]
Я ещё раз запустила программу полностью и проверила наличие всех необходимых формул.
Я сравнила поверхностные плотности атомарного водорода у себя и у Леруа, порядок величин в принципе совпадает, мне кажется даже, что у меня значения должны быть немного больше. 
А вот sigma_HI такая большая получилась наверное из-за большого угла наклона.
Леруа по этому поводу пишет:
> However, highly inclined galaxies show large scatter and systematically high velocity dispersions, likely because the velocity dispersion is significantly affected by projection effects.

А какой порядок должен быть в значении Sigma_s?

**Comment by Amarchuk** [comment]
Да, приведенная цитата с замечанием хорошая - собственно их Рис. (С1) это явно показывает. Но я в целом и писал выше, что в принципе такое может быть.

У Sigma_s сейчас не очень удобно бар цветов подобран, но в целом порядок очень похож на верный. 

Если сравнить с Рис. для это галактики у Лероя - все очень похоже, кроме Sigma_HI. У него значение  в кольце почти 10, у Вас - 2.5. Вы формулу напрямую взяли у Лероя и это правильно, вот только кубы данных в THINGS не в тех единицах. Надо вот так:

> $$\Sigma_{HI} [M_{sun} pc^{-2}] = 0.020 \cos i \times I_{21cm} [K km s^{-1}]$$
из https://arxiv.org/pdf/1609.03179.pdf $$\Sigma_{HI}[M_{sun} {pc}^{-2}] = 8840\times\frac{F_{HI}[Jy / beam \times km/s]}{bmaj\times bmin [arcsec]},$$
where the bmaj and bmin are the major and minor axis size of the beam, respectively. FHI is the flux detected across all velocity channels.

Чтобы перевести в кельвины в Walter написана формула
$$T[K] = 6.07\times 10^5\times S[Jy beam^{-1}]/(B_{maj}\times B_{min}),$$ где $B_{maj},B_{min}$ - размеры бима в секундах. Размеры beam надо смотреть в статье,  для 628 это было  для  ```NA``` данных  11.88 и 9.30 arcsec.  

Если не получится - пишите. Если получится около десятки - то все отлично.
