### ISSUE TITLE
результаты неустойчивости, промежуточное

### ISSUE THREAD

**Issue by Amarchuk** [LerkaKostuik/Course-work#7]
В Toomre.ipynb - это результаты для Q при текущих данных? 

Если да - то я попозже проверю чтобы с кодом все было и функциями верно (и поздравлю), а сейчас для улучшения результата надо сделать следующее:

* исправить Sigma_HI в #6
* нарисовать поверх контуры звездообразования на тех уровнях, что вам кажутся адекватными. Контуры можно добавить так:
`CS = plt.contour(X, Y, Halpha, levels=[-2.25, -1.], aspect='auto', alpha=0.5)`
* рисовать черно-белый уровень Q в адекватных масштабах - скажем от 2 до 4, а то сейчас не понятно по цвету, устойчива область или нет

**Comment by ValerieKostiuk** [comment]
Те результаты, которые были представлены в Toomre.ipynb, были подсчитаны с помощью вашей функции. Теперь я подправила свою и нынешний результат был получен уже моей функцией, в принципе они похожи с точностью до названия переменных (что неудивительно, ведь при написании своей программы я подсматривала в Вашу).
То, что получилось, было посчитано уже с обновлёнными данными.
Я пересчитала Sigma_HI, но результат не превышает 5 (я в принципе посчитала так же, как и Вы и учла фактор присутствия гелия(1.36)).
Мне также осталось посчитать SFR, я нашла у Вас все нужные формулы, только вот запуталась c d_L (luminosity distance).

**Comment by Amarchuk** [comment]
> были подсчитаны с помощью вашей функции.

Ага, понял. Это для практики и чтобы лучше разбираться?

> но результат не превышает 5

Я пересмотрел еще раз его рисунок - и мне кажется там максимум 7, а не 10 (ох уж этот логарифмический масштаб). У меня столько получается - 6.07x288x1000x0.5x2/(10.6x8.85x51x51), где 51 - это масштаб, 288 - это поток из куба HI (я просто взял значение, которое мне показалось на фитсе максимальным). Можете эту формулу использовать (хорошо бы еще потом азимутально усреднить чтоб сравнить, ну да это потом).

> только вот запуталась c d_L (luminosity distance).

На самом деле чтобы нарисовать контуры это не нужно - они не изменятся от того, что мы перенормируем величины к корректным Msun/kpc^2/year. Можно использовать ту формулу что я указал в коде, можно (2) вот отсюда https://arxiv.org/pdf/1105.4877.pdf и просто поделить на размер площадки в пк. В первом случае взять luminosity distance просто как расстояние до галактики. Для проверки можно будет сравнить полученные Sigma_SFR  с теми, что Вы упомянули в `notes.ipynb`
