### ISSUE TITLE
вопросы по последнему: shear, azim, Toomre

### ISSUE THREAD

**Issue by Amarchuk** [LerkaKostuik/Course-work#9]
Я новые issue буду заводить, если такие уже есть - можно переносить туда обсуждение.

Про shear:
* `shear_method*(1.8+i*0.2)` - чтобы так не делать (и было удобнее) почитайте про `enumerate` - это когда и индекс и значение сразу.
Например вместо `for i in range(1,7,1):` можно было бы `for i, shear_coeff in enumerate(np.linspace(2.0, 3.0, 6)):` (да, linspace тоже очень удобно)
* общее пожелание - пишите комментарии небольшие текстом между ячейками, чтоб было понятно что происходит. Я обычно из кода понимаю, но это не всегда удобно
* надо для проформы добавить график A(R)
* вообще результат интересный. Получается, что этот механизм хорошо подходит тоже для объяснения ЗО за счет только газа и вращения, но не в нижнем квадрате. Это отлично, что Вы его получили.

Про варьирование:
* все правильно делаете!
* Вы не загрузили `'array_errors_Sigma_H2.npy'`, поэтому я не смог сам попробовать - но думаю попробуйте boxplot без всех этих дополнительных параметров, которые там явно лишние, просто `plt.boxplot(array_errors, positions=np.array(np.arange(-25.,30.,5.)))`
* там теперь хорошо видно нелинейность - например при sigma_HI варьировании
* если возможно по вычислительным ресурсам - еще больше сделайте пределы изменения, но с тем же шагом
* суммарные картинки мне очень нравятся (где для разных данных показаны ошибки). Надо их только будет побольше/по-другому оформить
* я не смотрел везде, но вроде бы направление изменения совпадает с логикой, как должно быть (например добавляем звезд - газ становится менее устойчивым и т.д.)

Азим. усреднение:
* а какой максимальный радиус, где еще полный круг влезает по данным? Надо его отметить (т.к. у нас прямоугольник - то с какого-то момента усредняем только по части круга)
* во многом картина схожая с Лероем и это хорошо (и добавлять рисунки из статей в ноутбук - гуд, чтоб каждый раз не лезть сравнивать)
* последняя картинка - да, не так похоже. Видимо придется снять его данные по плотностям и остальному и тоже сравнить с нашими усредненными (и опять см. первый пункт, усреднял же он по полным кругам в отличие от нас)

**Comment by ValerieKostiuk** [comment]
По поводу метода shear, я вроде подправила код, как Вы писали,  и нарисовала график A(r).
Я также оцифровала данные Leroy по плотностям и сравнила со своими. 
Я только сейчас поняла, что возможно я неправильно оцифровала его данные по параметрам неустойчивости. У него там правда очень странная шкала, если в графике плотностей видно, что она логарифмическая, то в параметрах неустойчивости я не могу понять какая.

**Comment by Amarchuk** [comment]
Да, это правда, с графиками у него очень тяжело( В любом случае не стоит на этом фиксироваться, примерно сделали и можно обсуждать результат и что с ним делать.

> а какой максимальный радиус, где еще полный круг влезает по данным?

На 3.5 кпк примерно, я правильно понял? Не подскажите как нашли?

По коду - используйте list comprehension, это удобно. Можно вместо
```python
for dist in R:
    A.append(0.5 * (velocity_approx(dist) / dist - velocity_approx.deriv()(dist)))
```
писать 
```python
A = [(0.5 * (velocity_approx(dist) / dist - velocity_approx.deriv()(dist)) for dist in R]
```

По сравнению: не забывайте, что у Лероя немного другое расстояние. Вы его корректно пересчитываете при сравнении? Может поэтому графики немного разошлись (кажется все три для Лероя чуть сдвинуты дальше). И еще - наш газ изображен с множителем 1.4 или без него?

**Comment by ValerieKostiuk** [comment]
Отвечаю на вопросы по порядку:

-  > На 3.5 кпк примерно, я правильно понял? Не подскажите как нашли?

В файле get_data.ipynb есть изображение с расстояниями от центра галактики, скомпилированное под номером 211. 

- > По сравнению: не забывайте, что у Лероя немного другое расстояние. Вы его корректно пересчитываете при сравнении? 

У Лероя расстояния даны в arcsec, я их пересчитываю в кпк по формуле:
`r * np.pi / (180 *3600) * Distance * 10**3`

- > И еще - наш газ изображен с множителем 1.4 или без него?

При подсчёте параметра Тумре я использую этот множитель  
`Sigma_g = 1.36*(Sigma_HI_az[i]+ Sigma_H2_az[i])`
А при сравнении с Лероем я плотности газа по отдельности не умножала на этот коэффициент.   (Я только вспомнила, что это нужно было сделать, сейчас исправлю)

**Comment by Amarchuk** [comment]
> В файле get_data.ipynb есть изображение с расстояниями от центра галактики, скомпилированное под номером 211.

А как из него понять радиус? На глаз? Так не очень точно. В смысле я уверен, что Вы сделали это как-то более разумно, интересно где.

> У Лероя расстояния даны в arcsec

Да, тогда это не должно влиять. Но сдвиг кажется все равно есть. Впрочем, он небольшой. 
Надо домножить, станет ближе, но все еще не идеально совпадать. Сделайте, посмотрим.

С атомарным газом ситуация понятная - мы можем корректно его смотреть только до вертикальной черты, потом уже напрямую сравнивать не получится.

**Comment by ValerieKostiuk** [comment]
>  В смысле я уверен, что Вы сделали это как-то более разумно, интересно где.

Не хотела бы разрушать ваше мнение своей порядочности, но я правда в первый раз это значение взяла на глаз. И оказалось, что я ошиблась на четверть килопарсека( В файле Toomre.ipynb (скомпилированное под номером 15) я честно подобрала этот радиус в 3.25 кпк.
Так же в этом же файле посмотрите, что получилось после умножения плотностей газа на 1.36 .

**Comment by Amarchuk** [comment]
Брать на глаз - нормально, вопрос с какой точностью :) Я бы делал так, как Вы сейчас в итоге сделали. Ошибка меньше 10%, не так страшно.

Да, странное конечно у нас вышло различие по графикам: на HI не дотягивает (так и хочется еще раз умножить на 1.36), на CO - отстает. И все это еще до линии, где усреднение неполное. Загадка. Возможно в пределах ошибок все не так плохо или корень в технике усреднения (а как кстати Вы делали его?).

В любом случае я думаю стоит это зафиксировать и больше не тратить время на эту часть задачи.

**Comment by ValerieKostiuk** [comment]
При написании функции для азимутального усреднения, я так же как и Вы там же и считала стандартное отклонение. Сейчас я попробовала его применить к этим графиком и это ничего не улучшило( Я уже выложила новую версию кода

**Comment by Amarchuk** [comment]
Спасибо, я посмотрел. Всегда лучше понятно, что происходит, если график с ошибками.
Я думаю стоит признать, что разночтения в данных небольшие есть, это некритично.

Предлагаю дальше сделать следующее: 
- попробуйте разобраться как именно ищется наилучшее соответствие (надо будет понять что такое полнота/точность, это просто, но от этого вполне может заболеть голова) и найти его
- чтобы не забывать о науке - сделайте отдельный ноутбук со всеми результатами, что мы на текущий момент получили (что вы считаете значимым). Описание - картинка. Например "shear объясняет ЗО внутри галактики, но не снаружи для большого набора A" + картинка, где это видно. 

Как у вас с возможностями созвониться по интернету?

**Comment by ValerieKostiuk** [comment]
> попробуйте разобраться как именно ищется наилучшее соответствие (надо будет понять что такое полнота/точность, это просто, но от этого вполне может заболеть голова) и найти его

Я правильно понимаю, что полноту/точность вы упоминали в вашей статье?

> Как у вас с возможностями созвониться по интернету?

Конечно, у меня есть такая возможность (я использую Zoom или WhatsApp в таких случаях).

**Comment by Amarchuk** [comment]
Да. конечно, но лучше почитать что-то в духе http://bazhenov.me/blog/2012/07/21/classification-performance-evaluation.html. Или вообще попробовать с chi2 начать, но я думаю для него тоже не получится, как и у меня тогда. А еще можете свой способ придумать!

> Конечно, у меня есть такая возможность (я использую Zoom или WhatsApp в таких случаях).

Хорошо. Можно например созваниваться раз в неделю, если что-то новое сделано, чтобы я мог ответить на вопросы/обсудить

**Comment by ValerieKostiuk** [comment]
Я в ближайшие дни попробую разобраться с тем, что вы мне прислали. Если у меня не будет получаться, я вам напишу. 
Думаю после того как я эту часть работы сделаю, нам стоит созвониться.
Сhi2 я попробовала сделать, и да, конечно, я из него никакого результата не смогла вызволить.

**Comment by Amarchuk** [comment]
Хорошо. В целом, мне ничего не мешает и предварительные вопросы обсуждать голосом.

Про `Results.ipynb` - там где про ошибки сделайте еще пожалуйста совместную картинку более подробную (т.е. те как в исходном, просто объединить их в одну с подкартинками 2х3)

**Comment by ValerieKostiuk** [comment]
Посмотрите в Statistics.ipynb я попробовала найти precision, recall и F1.
> Про Results.ipynb - там где про ошибки сделайте еще пожалуйста совместную картинку более подробную (т.е. те как в исходном, просто объединить их в одну с подкартинками 2х3)

У меня пока что-то нормально не получается это сделать (картинки загружаются в ужасном качестве). Я позже попробую это сделать ещё раз.

**Comment by Amarchuk** [comment]
> вне 5 кпк всё не очень хорошо

Нужно хотя бы формальное обоснование такого решения. Иначе это подгон результатов получится, и хоть так люди в целом нередко делают, надо стараться избегать

Да, если что - можно было самой не считать все эти TP, TF, FN - в `sklearn` это есть. Но для понимания может так и полезно. Но насколько я вижу - там ошибка:
```python
if (Qeff_min[k][l] >= qlim) & (np.log10(H_alpha[k][l]) >= hlim):  
    FP+=1
                
if (Qeff_min[k][l] <= qlim) & (np.log10(H_alpha[k][l]) <= hlim):
    FN+=1
```

должны быть в первом случае знаки <= и <= (false positive - мы предсказываем сигнал, но его там нет), во втором случае >= и >= (false negative - мы предсказываем, что сигнала быть не должно, но на самом деле ЗО там есть). Запутаться тут конечно легко

Про 
> У меня пока что-то нормально не получается это сделать (картинки загружаются в ужасном качестве).

я не понял. Если что, в `plt.savefig` можно задать качество параметром `dpi`, например `dpi=300`

**Comment by ValerieKostiuk** [comment]
> Нужно хотя бы формальное обоснование такого решения. Иначе это подгон результатов получится, и хоть так люди в целом нередко делают, надо стараться избегать

Вы правы, так не стоило мне без объяснения делать. Я не в правильном порядке выставила эти ячейки в jupyter (сейчас они в правильном порядке). Я только лишь хотела посмотреть насколько сильно изменятся статистические данные, если я буду отбрасывать нижний квадрат. Ведь, если результат не сильно будет меняться, то на него вообще не стоит обращать внимания. А если он всё-таки сильно будет влиять, то тогда нужно будет думать, искать обоснования. У были какие-то идеи, что можно с этим квадратиком сделать, чтобы понять, почему у нас может быть там несоответствие (правда, я уже забыла что именно, сейчас буду вспоминать и записывать).
 
Я исправила, что вы мне написали . По сути F1 там не изменился, только recall и precision поменялись местами.

Также в Results.ipynb я загрузила те подкартинки.

**Comment by Amarchuk** [comment]
Я согласен про куб. Идея была, что может там сильно больше в среднем какие-то ошибки - это было бы хорошим обоснованием его откинуть. Впрочем, на самом деле он сейчас тоже нам дает информацию (зашумленную, но все же согласованную с искомым критерием).

В results.ipynb то что нужно, только в ошибках два раза ./images/Sigma_H2_vary.png.

В Statistics на последнем рисунке перепутаны заголовки (и вообще что-то странное случилось, сравните с рисунком по всем данным). И видно, что *принципиально* выкидывание данных за 5 кпк на результат не влияет. А почему у нас такие маленькие значения порога по logSFR? -14 - это прям какие-то оооочень нереальные значения, там точно в нужных единицах все? Я бы ожидал увидеть крайнее значение в районе -5 примерно.

Хм, кажется там вообще оси перепутаны почти везде местами. Возьмите на картинках recall например какое-то значение х и у и посмотрите, то ли значение на пересечении или не то.
(если что, `array[i][j]` - i это строка, j это столбец)

**Comment by ValerieKostiuk** [comment]
> А почему у нас такие маленькие значения порога по logSFR? -14

Я работала со значениями logH_aplha, а не с SFR. У меня как в первый раз не получилось перейти от H_alpha к SFR, так я ещё раз не пробовала это сделать.
Мне по полученному результату сложно понять, какое наилучшее соответствие (понятно, конечно, что чем больше F1, тем лучше). Как я поняла, вы в своих исследованиях выбрали сначала наилучшее предельное значение неустойчивости из Qmin, а потом уже стоили график F1(logSFR) и подбирали границу SFR. Я не могу понять, как мне сделать первый шаг по подбору порогового значения для Q.
Может мне как-то поварьировать приоритеты для точности и полноты при вычислении F-меры. Но тут нужно определиться тогда, чему отдавать приоритет?

**Comment by Amarchuk** [comment]
А, так понятно.

Сперва надо исправить рисунки, затем внимательно на них посмотреть. В целом может и не выйти найти соответствие таким способом.

Подбор порога Q: максимум оно равно примерно 3, можно посмотреть на графики F1 (и точности с полнотой) при Q=1,2,3 и дальше думать.

**Comment by ValerieKostiuk** [comment]
Посмотрите, я построила графики F1, precisoin и recall.  По итогам этих графиков наилучшее соответствие достигается при наименьшем из всех уровней logH_alpha.

**Comment by Amarchuk** [comment]
Проверьте пожалуйста, что на рисунке для < 5 кпк все правильно - там оси поменяны местами по сравнению с предыдущими. И тяжело про рисунки понимать без комментариев, для какого случая они нарисованы - приходится в код вчитываться. Вам тоже, если по прошествии какого-то времени вернетесь к ранее написанному, будет тяжело понять что для какого случая нарисовано.

Я правильно понял, что последние рисунки (где графики-линии) сделаны по всей площади? Действительно, не получается для них. А если без нижнего квадрата?

**Comment by ValerieKostiuk** [comment]
Посмотрите,что у меня получается на данный момент. Я попробовала убрать нижний, ситуация немного улучшилась. Также я попробовала поиграться с приоритетами для точности и полноты. Конечно, для того чтобы отдать тому или иному параметру приоритет нужно опять же обоснование ( почему-то мне кажется, что в рамках нашей задачи, мы можем отдать небольшой приоритет полноте, только у меня не очень получается сформулировать почему).

>  И тяжело про рисунки понимать без комментариев, для какого случая они нарисованы 

Я вроде старалась везде подписывать рисунки. Наверное где-то пропустила, извините.

**Comment by Amarchuk** [comment]
Радуюсь Вашей продуктивности! И не надо извиняться, нет необходимости.

Сперва немного замечаний: лучше на всех графиках рисовать оси от 0 до 1 (F1, точность, полнота), подписи к рисункам оставлять еще в виде комментариев перед собственно кодом ("построим отдельно графики для Q=1,2,3" и т.д.), чтоб читалось как текст.

К сожалению я не думаю, что можно довольно резонно отдать приоритет полноте перед точностью (хотя можно сказать что "мы хотим объяснить как можно большее число областей без сильного падения точности, а не малое с высокой точностью", тогда наверное можно было бы). И в целом уже кажется можно считать, что в каком-то смысле наилучшее соответствие при Qeffmin=3 и SFR=-14.1 примерно (т.к. у нас есть излом много где и F1 больше всего, включая recall-priority рисунки). Хотя, это и отчасти спекулятивно.

У меня две просьбы:
* нарисуйте пожалуйста карты с этими пределами, посмотрим и правда ли там визуально хорошее согласие (можно чуть поварьировать или штриховкой обе карты на одном рисунке, чтоб сразу было видно, насколько хорошее согласие)
* есть идея, как это можно попытаться сделать еще чуть более разумно: у нас есть верхняя и нижняя оценка для двухжидкостной модели. Давайте посчитаем F1, точность и полноту для двух карт одновременно? Это можно сделать разными способами, я предлагаю считать что у нас просто есть две карты с одинаковыми данными, на одних предсказания дает нижняя оценка, на вторых - верхняя. Если с этим не выйдет - то больше в эту сторону исследования не будем тратить время

**Comment by Amarchuk** [comment]
Есть кстати еще одна идея - посмотреть закон Киннекатта-Шмидта для разного порога Sigma_Halpha - вдруг это поможет также обосновать выбор наилучшего соответствия.

**Comment by ValerieKostiuk** [comment]
> есть идея, как это можно попытаться сделать еще чуть более разумно: у нас есть верхняя и нижняя оценка для двухжидкостной модели. Давайте посчитаем F1, точность и полноту для двух карт одновременно? Это можно сделать разными способами, я предлагаю считать что у нас просто есть две карты с одинаковыми данными, на одних предсказания дает нижняя оценка, на вторых - верхняя. Если с этим не выйдет - то больше в эту сторону исследования не будем тратить время

Я попробовала сделать, как вы написали. Посмотрите, правильно ли я Вас поняла.
Было бы здорово, если я это сделала правильно. Я получила F-меру, точность и полноту для полной карты, для обрезанной,  с приоритетом полноты для полной и обрезанной. Я сделала срезы для Q_lim=3 по этим картам и там получился чётко выраженный пик при log_Halpha = -14.15.

**Comment by Amarchuk** [comment]
Получилось хорошо! Это не совсем то, что я имел в виду, но так мне нравится даже больше. Кстати для меры без приоритета максимум там же :)

Добавьте этот результат к остальным и нарисуйте пожалуйста закон К-Ш для найденных областей. Две версии - с нижним квадратом и без него.

**Comment by ValerieKostiuk** [comment]
Не подскажите мне, пожалуйста, как мне получить рисунок для закона К-Ш. Точнее я не очень-то понимаю, как он должен выглядеть(

**Comment by Amarchuk** [comment]
Fig.5 из статьи https://arxiv.org/pdf/1804.07964.pdf. Просто взять эти области и по одной оси отложить суммарную плотность газа, по второй - SFR. Должно получиться что-то степенное. Можно дословно как в статье сделать.

**Comment by ValerieKostiuk** [comment]
Я попробовала нарисовать закон К-Ш, потом нашла, как вы это сделали, сделала также. Потом сравнила результаты, вроде похоже (правда Вашим методом рисунок красивее получается).
Посмотрите, пожалуйста, то ли я сделала, правильно ли я вас поняла.
На данном этапе я не смогу нарисовать линию, отражающую сам закон. Я могу только менять в заданных пределах [1.4,1.5] угол наклона. Но вот, чтобы отрегулировать её по высоте, мне нужно посчитать Sigma_SFR(этим я думаю сейчас и займусь).
Я правильно понимаю, что мне уже из полученных результатов нужно будет найти коэффициент пропорциональности в законе К_Ш?

**Comment by Amarchuk** [comment]
Выглядит нормально. 
* да, пора бы уже собраться и нормально посчитать SFR 
* а почему не получается найти линию? в принципе можно и на глаз подобрать первое приближение
* если я правильно понял - Вы закон К-Ш все же для всей карты (+обрезанной по 5 кпк) нарисовали - добавьте еще рисунок для К-Ш только внутри областей звездообразования (т.е. внутри выявленного порога, "красные области")

**Comment by ValerieKostiuk** [comment]
Я посчитала SFR и для него тоже нарисовала закон К-Ш. Я также пересчитала порог для обнаружения звездообразования  для Sigma_SFR, он оказался равным 0,19. Это нормально, что он больше значительно больше, чем в Вашем исследовании?
Я сделала вроде всё, что мы с Вами обсуждали в последний раз (сейчас поставлю галочки в обсуждении "Задачи") кроме gas cold phase (но там нужно вызволить из статьи металличность). Мне что-то ещё  прикладного нужно сделать, или я могу приступить уже к детальному изучению той статьи?

**Comment by Amarchuk** [comment]
Да, конечно карта SFR не совсем совпадает с показанной из статьи -  посмотрите Table 2 в трех областях в упомянутой Вами статье. Попробуйте на всякий случай еще раз аккуратно все проверить.
То, что порог оказался таким большим - странно, но теоретически возможно (но все равно много). Но опять же повод аккуратно пересчитать/перепроверить. Опять же любая информация о SFR из других статей может помочь.

Gas cold phase - там кроме металличности и не нужно больше ничего.

Про К-Ш - выглядит адекватно (на всех рисунках) и даже линия вполне соответствует.

**Comment by ValerieKostiuk** [comment]
Я пересчитала Sigma_SFR и теперь у меня порог для обнаружения звёздообразования равен 0.045.
Также во время поиска ошибок, я поняла, что я использовала в качестве расстояния до галактики значение 10.27, а Лерой в своей работе брал 9.3 (конечно во вселенский масштабах не немного, но всё-таки 1 Мпк). Конечно, это почти никак не повлияло на результат, у меня только Sigma_HI немного увеличился.

**Comment by Amarchuk** [comment]
Отлично! Эта величина уже похожа.

Да, такая ситуация увы в астрономии не редкость (хорошо что не в два раза различаются). А какое расстояние в итоге брали? Я помню что сравнивал несколько и в итоге брал то, что чаще использовалось и казалось более надежным (хотя это конечно не гарантия). В любом случае тут не так важно какое расстояние, главное чтобы везде одинаковое.

Вы тогда попробуйте сделать для последнего механизма, а я буду думать над публикацией, есть ли хорошие идеи что еще можно сделать или публиковать уже как есть. Думаю надо будет созвониться, если интернет позволяет.

И еще одно творческое задание: попробуйте сами для себя (или кому-то заинтересованному рассказать) еще раз проговорить что мы пытались найти или выяснить, получилось ли у нас и как еще можно подтвердить или опровергнуть нашу точку зрения.

**Comment by ValerieKostiuk** [comment]
> А какое расстояние в итоге брали?

Я везде сделала расстояние как у Лероя.

> Думаю надо будет созвониться, если интернет позволяет.

Интернет, конечно, позволяет. Я могу абсолютно в любое время.

По поводу того, что  ещё можно сделать, может мне подобрать параметр alpha_A для galactic shear таким же статистическим методом? Порог же для Sigma_SFR мы нашли.

**Comment by Amarchuk** [comment]
Да, можно это сделать - любая инициатива и эксперименты приветствуются. Только надо иметь в виду, что вообще говоря там порог может быть другой (в смысле не быть завязанным на то, что мы нашли).

**Comment by ValerieKostiuk** [comment]
Я смогла найти соответствие для SFR и alpha_A только при обрезанных данных . Получилось где-то SFR = 0.032 и alpha_A = 3.3.
Также я снова просмотрела [статью про металличность](https://arxiv.org/pdf/1910.07190.pdf). И опять убедилась, что там нет никакой ссылки на то, откуда можно извлечь нужные нам данные. Там, конечно, в статье указана формула, по которой они считают металличность. А для этого нужны I_[NII], I_[SII], I_[OIII] и I_[H_beta], но я так и не смогла понять, откуда они эти данные взяли (точнее где они находятся в общем доступе).  Может написать автору статьи и попросить у него, что нужно (это же вроде нормальная практика)?

**Comment by Amarchuk** [comment]
Интересный результат. В теории от упомянутых 2.5 не сильно отличается, и согласие тоже на картах довольно значимое. Надо картинку, где сравнивается с грав.неустойчивостью явно - чтобы было видно разницу (у нас есть две независимые, надо просто рядом их отрисовать). И написать, какие параметры (точность, полнота, F1) у нас для одного оптимального случая и для другого.

Про металличность: кажется они использовали эти данные https://musewide.aip.de/project/, но я там по координатам вроде нашу не нахожу галактику. Написать им можно со следующим вопросом: Таблица 2 (где по идее должна содержаться вся нужная нам информация) - написано, что она доступна онлайн, надо спросить где. Возможно на сайте самой статьи, но там нужен доступ (я не могу зайти, по идее университет должен иметь доступ).

В теории Вы хоть сейчас можете посчитать ColdPhase модель и никому не писать - обратите внимание на цвета на Рис. 14 в упомянутой статье. Там совсем небольшая вариация от 8.5 до 8.6. Т.е можно взять это значение и не париться.

**Comment by ValerieKostiuk** [comment]
> Надо картинку, где сравнивается с грав.неустойчивостью явно - чтобы было видно разницу (у нас есть две независимые, надо просто рядом их отрисовать). И написать, какие параметры (точность, полнота, F1) у нас для одного оптимального случая и для другого.

Я добавила это в Results.ipynb

Также я попробовала посчитать cold phase , считая металличность постоянным параметром. Получилось похоже. Меня просто смущает, что на картинке в статье области, где Z лежит в пределах от 8.4 до 8.6, распределены как-то дискретно. И большая часть просто серая (это значит, что значение металличности там приближено к нулю?). Я думаю, что будет как-то некорректно считать, что на всей области у нас Z постоянная. Я бы лучше написала автору (можно мне будет Вам прислать черновик этого письма, чтобы Вы просмотрели?)

**Comment by Amarchuk** [comment]
Спасибо! Так нагляднее. На самом деле грав. неустойчивость там еще как объясняет внизу, точнее предсказывает сильную неустойчивость. И у меня сразу два вопроса из этой картинки:

1. А почему на правой есть белые области? Какой параметр там ломается?
2. Видно, что обрезать кругом было не очень хорошо, значительный кусок (процентов 15) нижнего квадрата попадает. Лучше было бы по линии обрезать. И если так сделать, то чисто визуально кажется, что полнота слева должна быть больше (а она в 1.5 раза меньше!). Возможно цвета не очень хорошо подобраны и просто около Q=3 не видно неустойчивые. В общем я бы попросил обрезать по линии (и пересчитать, интересно же) и еще добавить такую же картинку, где было бы всего два цвета - неуст. и уст. (+ контуры ЗО другим). Могу лишь отметить, что такое в нашей работе постоянно - приходится переделывать :)

Про статью и последний механизм:
* формула - она из статьи? лучше добавлять ссылки, удобнее, и я понимать буду откуда
* карта интересная. Там 1. - это порог? Если да, то надо перерисовать, а то не видно. Кажется этот механизм будет слишком грубо предсказывать
* про написать: я раньше был молод и горяч и тоже торопился что-то делать :), но вообще хороший тон и достаточно прочитать статью, чтобы понять почему так. Они исследуют металличность в областях HII - ионизованного водорода, а они очевидно не во всех местах галактики есть, поэтому такие карты. Мне кажется валидным использовать такое допущение, учитывая что это единственный источник про металличности (можно поискать еще). Можно для строгости совместить их карту с нашей в фотошопе и считать только там, где есть данные. Или написать им с вопросом про онлайн данные и обойтись без фотошопа (но данных при этом больше очевидно не станет; и проверьте сперва онлайн статью, может там выложено все). Если надумаете все же написать - присылайте, посмотрю.

**Comment by ValerieKostiuk** [comment]
> А почему на правой есть белые области? Какой параметр там ломается?

Я посмотрела на данные, у меня в этих областях плотность газа отрицательная. Я вывела эти картинки в galactic_shear.ipynb внизу.

> В общем я бы попросил обрезать по линии (и пересчитать, интересно же) и еще добавить такую же картинку, где было бы всего два цвета - неуст. и уст. (+ контуры ЗО другим).

Я пересчитала статистические параметры для обрезанных по линии данных (надеюсь, я Вас правильно поняла)  и вроде ничего особо не поменялось. Эту работу я провела в Statistics.ipynb. В SFR.ipynb я добавила картинки с двумя цветами.

По поводу механизма cold phase я добавила комментарии: там область считается устойчивой, если Sigma_gas > Sigma_SO4. 
Я ещё раз пересмотрела онлайн статью и никакой ссылки на данные о металличности я не нашла, я только наткнулась на какие-то данные нашей галактики с MUSE VLT (только их так просто не скачать)

**Comment by Amarchuk** [comment]
> в этих областях плотность газа отрицательная.

Хм, а как такое может быть? У нас же газ не скудные квадраты из VENGA, там большие области. 

C cold phase добавьте пожалуйста к результатам (и статистики для нее тоже). Интересно получается.

Картинки с двумя цветами очень хорошие, сразу видно де есть согласие, а где нет.

> Эту работу я провела в Statistics.ipynb.

А Вы ее загрузили в репозиторий? Я не смог найти.

> я только наткнулась на какие-то данные нашей галактики с MUSE VLT (только их так просто не скачать)

Да, я тоже пытался их загрузить - но кажется (хотя они пишут обратное) обработанных там нет. Мне кажется, что искать дальше не стоит потраченных усилий, но конечное решение оставляю за Вами.

**Comment by ValerieKostiuk** [comment]
> Хм, а как такое может быть? У нас же газ не скудные квадраты из VENGA, там большие области.

Посмотрите в get_data.ipynb на ячейку скомпилированную под номером (44), я там выводила I_CO, там есть отрицательные значения (очень странно) , затем мы из этих данных получили Sigma_H2, а дальше и Sigma_gas. То есть отрицательные значения были изначально в фитсе. 

> А Вы ее загрузили в репозиторий? Я не смог найти.

Вы правы, я этот файл забыла загрузить сначала (уже исправила)

> Мне кажется, что искать дальше не стоит потраченных усилий, но конечное решение оставляю за Вами.

Я наверное, как Вы и предложили, посчитаю этот параметр для тех областей, для которых известна металличность, а для остальных я просто буду считать, что Z < 1. Не знаю насколько это разумно, но может что-то получится.

**Comment by Amarchuk** [comment]
Хм, а как Вы там видите отрицательные? Я поискал в фитсе - кажется там только совсем с плохим сигнал/шум отрицательные (в любом случае это минорная проблема, но надо понять). 

Если честно, трудно разобраться со статистикой. Получилось, что при r<4.5 кпк F,recall, precision можно считать теми же, верно?

> Я наверное, как Вы и предложили, посчитаю этот параметр для тех областей, для которых известна металличность, а для остальных я просто буду считать, что Z < 1. Не знаю насколько это разумно, но может что-то получится.

Попробуйте, это будет честнее. Сложно только относительно будет совместить и извлечь данные из их карты.

**Comment by ValerieKostiuk** [comment]
Посмотрите в cold_phase.ipynb, я попробовала совместить карты. Получилось ,как по мне, достаточно правдоподобно.

**Comment by Amarchuk** [comment]
Правдоподобно, но не до конца. Там нижний край спирали и ответвления рядом кажется немного вылезает и верхняя тоже. Если что - кажется проще совместить не это изображение, а самое первое (Halpha)

**Comment by ValerieKostiuk** [comment]
Посмотрите я подправила карту металличности и посчитала cold gas phase, также в Statistics.ipynb я нашла наилучшее соответствие и Sigma_SFR. 

> а как Вы там видите отрицательные?

Посмотрите в get_data.ipynb на ячейку скомпилированную под номером (10), я там отобразила карту I_CO с максимальным значением 0, и там видны отрицательные области.

**Comment by Amarchuk** [comment]
Отлично!

Про cold_phase - а как Вы в [120] нарисовали то, что слева? И мне все еще кажется, что нижний край не совсем корректно совмещен, например по этому сгущению темному ближе к левой стороне. Я, когда требовалось что-то подобное делать - брал в фотошопе два слоя, делал их полупрозрачными и смотрел, хорошо ли совместилось. Можете кстати с рисунка справа (который области HII) взять все пиксели больше порога и посмотреть, как их контуры ложатся слева (будет видно, что не совсем ровно). 

Да, а результат интересный пока (лучший даже похоже).

> Посмотрите в get_data.ipynb

Да, и правда! Хорошо, что мы поняли это. Надо бы конечно проверить, что сумма газов Sigma_HI+Sigma_CO нигде не попортилось из-за этого, но можно и не, области нам эти не очень интересны как мы знаем, а отрицательные величины малы.

> я нашла наилучшее соответствие и Sigma_SFR.

Да, это тот пример, где отлично сразу находится и глазами это тоже видно!

Давайте еще раз уточним с металличностями аккуратнее (совмещение карт), судя по результатам - это очень важно, поскольку результат пока самый выразительный для них.

И да, если Вы решили так совмещать - надо наверное отдельным цветом отметить области без данных. И привести результаты для постоянной металличности. Это тоже важно. Хочется всего и сразу :)

**Comment by ValerieKostiuk** [comment]
Посмотрите, пожалуйста, я попыталась улучшить карту металличности. Я сначала в фотошопе, как Вы и написали, попробовала совместить карты. Затем я уже вручную добавляла и убирала данные.
Я думаю не удивительно, что получается достаточно хороший результат, ведь этот параметр гравитационной неустойчивости считается с помощью Sigma_SFR.

**Comment by Amarchuk** [comment]
А как Вы в [23] нарисовали то, что слева? Вручную отобразили цвет значениям?

Все еще не идеально, но видимо у нас разные соображения о том, что именно там надо совместить (лучше было бы взять один из нижних рисунков из статьи, там еще и координаты есть - если будет время и желание). 

> Я думаю не удивительно, что получается достаточно хороший результат, ведь этот параметр гравитационной неустойчивости считается с помощью Sigma_SFR.

Это очень хорошее соображение! Действительно, видимо поэтому получаются такие "ровные" контуры совпадения с SFR. 

Что еще можно тут сделать - посчитать статистики как для остальных (очень высокие значения должны получиться) и нарисовать карты как в последних ячейках, только вместо уровней SFR - уровни плотностей газа к звездной плотности f_g из формулы (несколько разного цвета линиями - посмотрите какие лучше).

А, и карту слева последнюю переделать - надо отдельным цветом отметить области без данных (возможно если там присвоить этим пикселям NaN, то выйдет само собой)

**Comment by ValerieKostiuk** [comment]
Я думаю сначала доделаю работу, связанную с картой cold phase, затем приступлю к другой части работы (о которой вы мне вчера написали).
Я в фотошопе совместила карты металличности и H_alpha уже по координатам, и оказалось они правда очень хорошо друг с другом коррелируют. Думаю сейчас карта металличности достаточно правдоподобная.
 Я также посчитала статистику для этого параметра , я добавлю её  Results.ipynb.
  

>  нарисовать карты как в последних ячейках, только вместо уровней SFR - уровни плотностей газа к звездной плотности f_g из формулы

я правильно понимаю, что мне нужно взять в этом случае только уровни f_g, если да, то я не могу подобрать их.

**Comment by Amarchuk** [comment]
О, вот теперь они совпали! Отлично.

> я правильно понимаю, что мне нужно взять в этом случае только уровни f_g, если да, то я не могу подобрать их.

Того, что Вы нарисовали - достаточно, я понял что к чему.

Добавьте теперь результаты для Z=const и Z=map (с как и ранее с пустыми клетками, где без карты) к результатам (и статистики - для обеих) и с этой частью можно завершить.
